# Minify content
[build.processing]
    skip_processing = false
[build.processing.css]
    bundle = true
    minify = true
[build.processing.js]
    bundle = true
    minify = true
[build.processing.html]
    pretty_urls = true
[build.processing.images]
    compress = true

# Disable preview processing
[context.deploy-preview.processing]
    skip_processing = true
